version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-west-3
    ECR_REPOSITORY_BACKEND: tech-backend
    ECR_REPOSITORY_FRONTEND: tech-frontend
    EC2_INSTANCE_ID: i-0348c30d1346185d8
    EC2_HOME: /home/ubuntu

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - apt-get update -y
      - apt-get install -y jq awscli

  pre_build:
    commands:
      - echo "Logando no ECR..."
      - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 572692059120.dkr.ecr.eu-west-3.amazonaws.com

  build:
    commands:
      - echo "Construindo imagem backend..."
      - docker build -t tech-backend ./backend

      - echo "Construindo imagem frontend..."
      - docker build -t tech-frontend ./frontend

  post_build:
    commands:
      - echo "Tagging imagens..."
      - docker tag tech-backend:latest 572692059120.dkr.ecr.eu-west-3.amazonaws.com/tech-backend:latest
      - docker tag tech-frontend:latest 572692059120.dkr.ecr.eu-west-3.amazonaws.com/tech-frontend:latest

      - echo "Push para ECR..."
      - docker push 572692059120.dkr.ecr.eu-west-3.amazonaws.com/tech-backend:latest
      - docker push 572692059120.dkr.ecr.eu-west-3.amazonaws.com/tech-frontend:latest

      - echo "Executando deploy via SSM na EC2..."
      - |
        aws ssm send-command \
          --instance-ids "$EC2_INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy Blog App" \
          --parameters 'commands=[
            "echo Logging into ECR...",
            "/usr/bin/aws ecr get-login-password --region eu-west-3 | sudo /usr/bin/docker login --username AWS --password-stdin 572692059120.dkr.ecr.eu-west-3.amazonaws.com",
            "echo Pulling new images...",
            "sudo /usr/bin/docker pull 572692059120.dkr.ecr.eu-west-3.amazonaws.com/tech-backend:latest",
            "sudo /usr/bin/docker pull 572692059120.dkr.ecr.eu-west-3.amazonaws.com/tech-frontend:latest",
            "echo Restarting containers...",
            "cd /home/ubuntu/Auto-Generated-Blog/infra",
            "sudo /usr/bin/docker compose down || true",
            "sudo /usr/bin/docker compose up -d",
            "echo Deploy completo!"
          ]' \
          --timeout-seconds 900

artifacts:
  files:
    - "**/*"
